/**
 * IntegriSense AI — Incident & Approval Models
 *
 * Defines the schemas for detected anomalies, root cause analysis (RCA),
 * recovery recommendations, agent activities, and human-in-the-loop approvals.
 */

export type IncidentSeverity = 'low' | 'medium' | 'high' | 'critical';
export type IncidentStatus = 'active' | 'investigating' | 'mitigating' | 'resolved';

export interface Incident {
  id: string;                 // Unique identifier
  integrationId: string;      // Related integration pipeline
  integrationName: string;
  severity: IncidentSeverity;
  status: IncidentStatus;
  detectedAt: string;         // ISO Timestamp
  resolvedAt?: string;        // ISO Timestamp (optional)
  triggerReason: string;      // What triggered the incident detection
  rootCause?: string;         // RCA description
  metricsSnapshot: {
    latencyMs: number;
    errorRate: number;
    queueDepth: number;
    dlqCount: number;
    zScore?: number;
    riskScore?: number;
  };
  rca?: RootCauseAnalysis;    // Generated by RCA Agent
  recovery?: RecoveryAction;  // Generated by Recovery Agent
}

export interface RootCauseAnalysis {
  rootCause: string;          // Direct cause description
  explanation: string;        // Detailed explanation by Gemini
  evidence: string[];         // Numerical or log evidence supporting the analysis
  affectedSystem: string;     // Specific component failing (e.g., Salesforce OAuth endpoint)
  confidence: number;         // Confidence score (0.0 - 1.0)
  contributingFactors: string[];
  analyzedAt: string;
}

export interface RecoveryAction {
  id: string;                 // Recovery recommendation ID
  incidentId: string;
  playbookName: string;       // Name of recovery playbook (e.g., Flush Queue)
  recommendedAction: string;  // Detailed action description
  expectedImpact: string;     // Expected result of taking action
  riskLevel: 'low' | 'medium' | 'high';
  riskDescription: string;
  rollbackPlan: string;       // Instructions on how to undo if fails
  approvalRequired: boolean;
  status: 'pending' | 'approved' | 'rejected' | 'executed' | 'failed';
  decidedBy?: string;         // Name/ID of operator
  decidedAt?: string;         // ISO Timestamp
}

export interface AgentActivity {
  id: string;
  incidentId: string;
  agentName: 'MonitorAgent' | 'RcaAgent' | 'PredictionAgent' | 'RecoveryAgent' | 'Orchestrator';
  activityType: 'analysis' | 'tool_call' | 'recommendation' | 'decision';
  message: string;            // Log entry describing what the agent did
  timestamp: string;          // ISO Timestamp
}
