/**
 * IntegriSense AI — Risk Prediction Model
 *
 * Defines the schema for failure predictions generated by the Prediction Agent.
 */

export type RiskLevel = 'low' | 'medium' | 'high' | 'critical';

export interface FailureProbability {
  integrationId: string;
  integrationName: string;
  riskScore: number;                 // Deterministic risk score (0.0 - 1.0)
  riskLevel: RiskLevel;
  predictedFailureWindowHours: number; // Estimated hours until failure occurs
  confidence: number;                // Score indicating prediction confidence (0.0 - 1.0)
  contributingFactors: {
    factor: string;
    weight: number;                 // Relative impact of factor (0.0 - 1.0)
  }[];
  explanation?: string;              // Gemini explanation of the contributing factors
  lastUpdated: string;               // ISO Timestamp
}
